version: '3'

services:  

  redis:
    image: redis:latest
    hostname: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./scripts/run_server.sh
    volumes:
      - .:/app 
    ports:
      - "5000:5000"
    links:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/run_celery.sh
    volumes:
      - .:/app
    links:
      - redis